name: Addition test

on:
  push:
    branches:
      - main

jobs:
  run_code:
    name: Run Python Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python --version
      - run: python Day49.py

  run_tests:
    name: Run Python Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python --version
      - run: python -m pip install -r requirements_dev.txt
      - run: pytest